theme: jekyll-theme-minimal

name: Jack Williams
title: Jack Williams, Appendix 1
markdown: kramdown
description: Am I still allowed to say I have a two page resume? 
logo: /assets/img/f1rocketengine.jpg
