theme: jekyll-theme-minimal

name: Jack Williams
title: Projects
markdown: kramdown
#description: The great thing about procrastination is that you don't have any excuse to put it off.
logo: /assets/img/f1rocketengine.jpg
